// <auto-generated />
using System;
using InterviewCracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InterviewCracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251002123800_UpdateCompanyCollegeAssignments")]
    partial class UpdateCompanyCollegeAssignments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("InterviewCracker.Models.CodingQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("ContributorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Difficulty")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SampleInput")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SampleOutput")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Solution")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Tags")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("Topic")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContributorId");

                    b.ToTable("CodingQuestions");
                });

            modelBuilder.Entity("InterviewCracker.Models.College", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4")
                        .HasMaxLength(1000);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Colleges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 9, 2, 18, 8, 0, 499, DateTimeKind.Local).AddTicks(2794),
                            Description = "Premier engineering college",
                            ImageUrl = "/images/mit.jpg",
                            IsActive = true,
                            Location = "Pune",
                            Name = "MIT College of Engineering"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 9, 7, 18, 8, 0, 499, DateTimeKind.Local).AddTicks(3343),
                            Description = "Government engineering college",
                            ImageUrl = "/images/coep.jpg",
                            IsActive = true,
                            Location = "Pune",
                            Name = "COEP Technological University"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 9, 12, 18, 8, 0, 499, DateTimeKind.Local).AddTicks(3359),
                            Description = "Private technical university",
                            ImageUrl = "/images/vit.jpg",
                            IsActive = true,
                            Location = "Vellore",
                            Name = "VIT Vellore"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 9, 17, 18, 8, 0, 499, DateTimeKind.Local).AddTicks(3363),
                            Description = "Indian Institute of Technology",
                            ImageUrl = "/images/iit.jpg",
                            IsActive = true,
                            Location = "Mumbai",
                            Name = "IIT Bombay"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 9, 22, 18, 8, 0, 499, DateTimeKind.Local).AddTicks(3366),
                            Description = "National Institute of Technology",
                            ImageUrl = "/images/nit.jpg",
                            IsActive = true,
                            Location = "Trichy",
                            Name = "NIT Trichy"
                        });
                });

            modelBuilder.Entity("InterviewCracker.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("Website")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollegeId = 1,
                            CreatedDate = new DateTime(2025, 9, 2, 18, 8, 0, 499, DateTimeKind.Local).AddTicks(5637),
                            Description = "Technology company",
                            IsActive = true,
                            LogoUrl = "/images/microsoft.jpg",
                            Name = "Microsoft",
                            Website = "https://microsoft.com"
                        },
                        new
                        {
                            Id = 2,
                            CollegeId = 3,
                            CreatedDate = new DateTime(2025, 9, 7, 18, 8, 0, 499, DateTimeKind.Local).AddTicks(6025),
                            Description = "Search and technology company",
                            IsActive = true,
                            LogoUrl = "/images/google.jpg",
                            Name = "Google",
                            Website = "https://google.com"
                        },
                        new
                        {
                            Id = 3,
                            CollegeId = 2,
                            CreatedDate = new DateTime(2025, 9, 12, 18, 8, 0, 499, DateTimeKind.Local).AddTicks(6034),
                            Description = "E-commerce and cloud computing",
                            IsActive = true,
                            LogoUrl = "/images/amazon.jpg",
                            Name = "Amazon",
                            Website = "https://amazon.com"
                        },
                        new
                        {
                            Id = 4,
                            CollegeId = 2,
                            CreatedDate = new DateTime(2025, 9, 14, 18, 8, 0, 499, DateTimeKind.Local).AddTicks(6038),
                            Description = "IT Services and Consulting",
                            IsActive = true,
                            LogoUrl = "/images/tcs.jpg",
                            Name = "TCS",
                            Website = "https://tcs.com"
                        },
                        new
                        {
                            Id = 5,
                            CollegeId = 3,
                            CreatedDate = new DateTime(2025, 9, 17, 18, 8, 0, 499, DateTimeKind.Local).AddTicks(6041),
                            Description = "Consumer electronics company",
                            IsActive = true,
                            LogoUrl = "/images/apple.jpg",
                            Name = "Apple",
                            Website = "https://apple.com"
                        },
                        new
                        {
                            Id = 6,
                            CollegeId = 3,
                            CreatedDate = new DateTime(2025, 9, 22, 18, 8, 0, 499, DateTimeKind.Local).AddTicks(6045),
                            Description = "Social media and technology",
                            IsActive = true,
                            LogoUrl = "/images/meta.jpg",
                            Name = "Meta",
                            Website = "https://meta.com"
                        },
                        new
                        {
                            Id = 7,
                            CollegeId = 4,
                            CreatedDate = new DateTime(2025, 9, 20, 18, 8, 0, 499, DateTimeKind.Local).AddTicks(6048),
                            Description = "Investment banking and financial services",
                            IsActive = true,
                            LogoUrl = "/images/goldman.jpg",
                            Name = "Goldman Sachs",
                            Website = "https://goldmansachs.com"
                        },
                        new
                        {
                            Id = 8,
                            CollegeId = 4,
                            CreatedDate = new DateTime(2025, 9, 24, 18, 8, 0, 499, DateTimeKind.Local).AddTicks(6051),
                            Description = "Semiconductor and technology",
                            IsActive = true,
                            LogoUrl = "/images/intel.jpg",
                            Name = "Intel",
                            Website = "https://intel.com"
                        },
                        new
                        {
                            Id = 9,
                            CollegeId = 5,
                            CreatedDate = new DateTime(2025, 9, 26, 18, 8, 0, 499, DateTimeKind.Local).AddTicks(6055),
                            Description = "IT Services and Digital transformation",
                            IsActive = true,
                            LogoUrl = "/images/infosys.jpg",
                            Name = "Infosys",
                            Website = "https://infosys.com"
                        },
                        new
                        {
                            Id = 10,
                            CollegeId = 5,
                            CreatedDate = new DateTime(2025, 9, 28, 18, 8, 0, 499, DateTimeKind.Local).AddTicks(6058),
                            Description = "IT Services and Consulting",
                            IsActive = true,
                            LogoUrl = "/images/wipro.jpg",
                            Name = "Wipro",
                            Website = "https://wipro.com"
                        },
                        new
                        {
                            Id = 11,
                            CollegeId = 0,
                            CreatedDate = new DateTime(2025, 9, 30, 18, 8, 0, 499, DateTimeKind.Local).AddTicks(6062),
                            Description = "Technology and consulting services",
                            IsActive = true,
                            LogoUrl = "/images/ibm.jpg",
                            Name = "IBM",
                            Website = "https://ibm.com"
                        },
                        new
                        {
                            Id = 12,
                            CollegeId = 0,
                            CreatedDate = new DateTime(2025, 10, 1, 18, 8, 0, 499, DateTimeKind.Local).AddTicks(6065),
                            Description = "Professional services company",
                            IsActive = true,
                            LogoUrl = "/images/accenture.jpg",
                            Name = "Accenture",
                            Website = "https://accenture.com"
                        });
                });

            modelBuilder.Entity("InterviewCracker.Models.MCQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("ContributorId")
                        .HasColumnType("int");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("varchar(1) CHARACTER SET utf8mb4")
                        .HasMaxLength(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Difficulty")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Explanation")
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Tags")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("Topic")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContributorId");

                    b.ToTable("MCQs");
                });

            modelBuilder.Entity("InterviewCracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("GitHubProfile")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LinkedInProfile")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("Organization")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.Property<string>("Role")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 10, 2, 18, 8, 0, 497, DateTimeKind.Local).AddTicks(7017),
                            Email = "admin@admin.com",
                            IsActive = true,
                            Name = "System Admin",
                            Password = "admin123",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 10, 2, 18, 8, 0, 497, DateTimeKind.Local).AddTicks(7553),
                            Email = "contributor@test.com",
                            IsActive = true,
                            Name = "John Doe",
                            Password = "test123",
                            Role = "Contributor"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 10, 2, 18, 8, 0, 497, DateTimeKind.Local).AddTicks(7690),
                            Email = "student@test.com",
                            IsActive = true,
                            Name = "Jane Smith",
                            Password = "test123",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("InterviewCracker.Models.CodingQuestion", b =>
                {
                    b.HasOne("InterviewCracker.Models.College", null)
                        .WithMany()
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewCracker.Models.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewCracker.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InterviewCracker.Models.MCQ", b =>
                {
                    b.HasOne("InterviewCracker.Models.College", null)
                        .WithMany()
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewCracker.Models.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewCracker.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
