// <auto-generated />
using System;
using InterviewCracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InterviewCracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251002154847_UpdateCompanyLogos")]
    partial class UpdateCompanyLogos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("InterviewCracker.Models.CodingQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("ContributorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Difficulty")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SampleInput")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SampleOutput")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Solution")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Tags")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("Topic")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContributorId");

                    b.ToTable("CodingQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollegeId = 3,
                            CompanyId = 2,
                            ContributorId = 2,
                            CreatedDate = new DateTime(2025, 9, 28, 21, 18, 46, 942, DateTimeKind.Local).AddTicks(5351),
                            Description = "Find two numbers in an array that add up to a target sum and return their indices.",
                            Difficulty = "Easy",
                            IsActive = true,
                            IsApproved = true,
                            Problem = "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.",
                            SampleInput = "nums = [2,7,11,15], target = 9",
                            SampleOutput = "[0,1]",
                            Solution = "Use a hash map to store complements and their indices for O(n) solution.",
                            Tags = "hash map, two pointers",
                            Title = "Two Sum",
                            Topic = "Arrays",
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            CollegeId = 1,
                            CompanyId = 1,
                            ContributorId = 2,
                            CreatedDate = new DateTime(2025, 10, 1, 21, 18, 46, 942, DateTimeKind.Local).AddTicks(5882),
                            Description = "Reverse the direction of pointers in a singly linked list.",
                            Difficulty = "Medium",
                            IsActive = true,
                            IsApproved = true,
                            Problem = "Given the head of a singly linked list, reverse the list, and return the reversed list.",
                            SampleInput = "head = [1,2,3,4,5]",
                            SampleOutput = "[5,4,3,2,1]",
                            Solution = "Use iterative approach with three pointers: prev, current, and next.",
                            Tags = "linked list, pointers",
                            Title = "Reverse Linked List",
                            Topic = "Linked Lists",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("InterviewCracker.Models.College", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4")
                        .HasMaxLength(1000);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Colleges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 9, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(5054),
                            Description = "Premier engineering college",
                            ImageUrl = "/images/colleges/MIT College of Engineering.jpg",
                            IsActive = true,
                            Location = "Pune",
                            Name = "MIT College of Engineering"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 9, 7, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(5479),
                            Description = "Government engineering college",
                            ImageUrl = "/images/colleges/COEP Technological University.jpg",
                            IsActive = true,
                            Location = "Pune",
                            Name = "COEP Technological University"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 9, 12, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(5493),
                            Description = "Private technical university",
                            ImageUrl = "/images/colleges/VIT Vellore.jpg",
                            IsActive = true,
                            Location = "Vellore",
                            Name = "VIT Vellore"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 9, 17, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(5496),
                            Description = "Indian Institute of Technology",
                            ImageUrl = "/images/colleges/IIT Bombay.webp",
                            IsActive = true,
                            Location = "Mumbai",
                            Name = "IIT Bombay"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 9, 22, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(5499),
                            Description = "National Institute of Technology",
                            ImageUrl = "/images/colleges/NIT Trichy.jpg",
                            IsActive = true,
                            Location = "Trichy",
                            Name = "NIT Trichy"
                        });
                });

            modelBuilder.Entity("InterviewCracker.Models.CollegeCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CollegeId", "CompanyId")
                        .IsUnique();

                    b.ToTable("CollegeCompanies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollegeId = 1,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(8914),
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            CollegeId = 1,
                            CompanyId = 2,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9136),
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            CollegeId = 1,
                            CompanyId = 3,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9143),
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            CollegeId = 1,
                            CompanyId = 4,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9146),
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            CollegeId = 1,
                            CompanyId = 12,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9148),
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            CollegeId = 2,
                            CompanyId = 2,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9220),
                            IsActive = true
                        },
                        new
                        {
                            Id = 7,
                            CollegeId = 2,
                            CompanyId = 3,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9222),
                            IsActive = true
                        },
                        new
                        {
                            Id = 8,
                            CollegeId = 2,
                            CompanyId = 8,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9225),
                            IsActive = true
                        },
                        new
                        {
                            Id = 9,
                            CollegeId = 2,
                            CompanyId = 9,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9227),
                            IsActive = true
                        },
                        new
                        {
                            Id = 10,
                            CollegeId = 2,
                            CompanyId = 12,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9230),
                            IsActive = true
                        },
                        new
                        {
                            Id = 11,
                            CollegeId = 3,
                            CompanyId = 2,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9232),
                            IsActive = true
                        },
                        new
                        {
                            Id = 12,
                            CollegeId = 3,
                            CompanyId = 4,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9235),
                            IsActive = true
                        },
                        new
                        {
                            Id = 13,
                            CollegeId = 3,
                            CompanyId = 5,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9237),
                            IsActive = true
                        },
                        new
                        {
                            Id = 14,
                            CollegeId = 3,
                            CompanyId = 6,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9240),
                            IsActive = true
                        },
                        new
                        {
                            Id = 15,
                            CollegeId = 3,
                            CompanyId = 7,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9242),
                            IsActive = true
                        },
                        new
                        {
                            Id = 16,
                            CollegeId = 4,
                            CompanyId = 1,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9244),
                            IsActive = true
                        },
                        new
                        {
                            Id = 17,
                            CollegeId = 4,
                            CompanyId = 2,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9247),
                            IsActive = true
                        },
                        new
                        {
                            Id = 18,
                            CollegeId = 4,
                            CompanyId = 3,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9249),
                            IsActive = true
                        },
                        new
                        {
                            Id = 19,
                            CollegeId = 4,
                            CompanyId = 11,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9252),
                            IsActive = true
                        },
                        new
                        {
                            Id = 20,
                            CollegeId = 4,
                            CompanyId = 12,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9254),
                            IsActive = true
                        },
                        new
                        {
                            Id = 21,
                            CollegeId = 5,
                            CompanyId = 2,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9257),
                            IsActive = true
                        },
                        new
                        {
                            Id = 22,
                            CollegeId = 5,
                            CompanyId = 8,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9259),
                            IsActive = true
                        },
                        new
                        {
                            Id = 23,
                            CollegeId = 5,
                            CompanyId = 9,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9262),
                            IsActive = true
                        },
                        new
                        {
                            Id = 24,
                            CollegeId = 5,
                            CompanyId = 10,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9264),
                            IsActive = true
                        },
                        new
                        {
                            Id = 25,
                            CollegeId = 5,
                            CompanyId = 12,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(9266),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("InterviewCracker.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("Website")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 9, 2, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(7468),
                            Description = "Technology company",
                            IsActive = true,
                            LogoUrl = "/images/companies/microsoft.png",
                            Name = "Microsoft",
                            Website = "https://microsoft.com"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 9, 7, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(7699),
                            Description = "Search and technology company",
                            IsActive = true,
                            LogoUrl = "/images/companies/google.png",
                            Name = "Google",
                            Website = "https://google.com"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 9, 12, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(7707),
                            Description = "E-commerce and cloud computing",
                            IsActive = true,
                            LogoUrl = "/images/companies/amazon.jpg",
                            Name = "Amazon",
                            Website = "https://amazon.com"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 9, 17, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(7711),
                            Description = "Consumer electronics company",
                            IsActive = true,
                            LogoUrl = "/images/companies/apple.png",
                            Name = "Apple",
                            Website = "https://apple.com"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 9, 22, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(7713),
                            Description = "Social media and technology",
                            IsActive = true,
                            LogoUrl = "/images/companies/meta.png",
                            Name = "Meta",
                            Website = "https://meta.com"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 9, 24, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(7717),
                            Description = "Electric vehicles and clean energy",
                            IsActive = true,
                            LogoUrl = "/images/companies/tesla.png",
                            Name = "Tesla",
                            Website = "https://tesla.com"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 9, 26, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(7720),
                            Description = "Streaming entertainment service",
                            IsActive = true,
                            LogoUrl = "/images/companies/Netflix.png",
                            Name = "Netflix",
                            Website = "https://netflix.com"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 9, 27, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(7723),
                            Description = "IT Services and Consulting",
                            IsActive = true,
                            LogoUrl = "/images/companies/tcs.png",
                            Name = "TCS",
                            Website = "https://tcs.com"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 9, 28, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(7726),
                            Description = "IT Services and Digital transformation",
                            IsActive = true,
                            LogoUrl = "/images/companies/Infosys.png",
                            Name = "Infosys",
                            Website = "https://infosys.com"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 9, 29, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(7729),
                            Description = "IT Services and Consulting",
                            IsActive = true,
                            LogoUrl = "/images/companies/Wipro.png",
                            Name = "Wipro",
                            Website = "https://wipro.com"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 9, 30, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(7732),
                            Description = "Investment banking and financial services",
                            IsActive = true,
                            LogoUrl = "/images/companies/Goldman Sachs.png",
                            Name = "Goldman Sachs",
                            Website = "https://goldmansachs.com"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 10, 1, 21, 18, 46, 941, DateTimeKind.Local).AddTicks(7735),
                            Description = "Technology and consulting services",
                            IsActive = true,
                            LogoUrl = "/images/companies/ibm.png",
                            Name = "IBM",
                            Website = "https://ibm.com"
                        });
                });

            modelBuilder.Entity("InterviewCracker.Models.MCQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("ContributorId")
                        .HasColumnType("int");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("varchar(1) CHARACTER SET utf8mb4")
                        .HasMaxLength(1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Difficulty")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Explanation")
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Tags")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("Topic")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContributorId");

                    b.ToTable("MCQs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollegeId = 3,
                            CompanyId = 2,
                            ContributorId = 2,
                            CorrectAnswer = "B",
                            CreatedDate = new DateTime(2025, 9, 27, 21, 18, 46, 942, DateTimeKind.Local).AddTicks(2216),
                            Difficulty = "Medium",
                            Explanation = "Binary search divides the search space in half with each comparison, resulting in O(log n) time complexity.",
                            IsActive = true,
                            IsApproved = true,
                            OptionA = "O(n)",
                            OptionB = "O(log n)",
                            OptionC = "O(n^2)",
                            OptionD = "O(1)",
                            Question = "What is the time complexity of binary search?",
                            Tags = "binary search, time complexity",
                            Topic = "Algorithms",
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            CollegeId = 3,
                            CompanyId = 2,
                            ContributorId = 2,
                            CorrectAnswer = "B",
                            CreatedDate = new DateTime(2025, 9, 29, 21, 18, 46, 942, DateTimeKind.Local).AddTicks(2528),
                            Difficulty = "Easy",
                            Explanation = "Stack follows Last In First Out (LIFO) principle where the last element added is the first one to be removed.",
                            IsActive = true,
                            IsApproved = true,
                            OptionA = "Queue",
                            OptionB = "Stack",
                            OptionC = "Array",
                            OptionD = "Linked List",
                            Question = "Which data structure uses LIFO principle?",
                            Tags = "stack, LIFO",
                            Topic = "Data Structures",
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            CollegeId = 1,
                            CompanyId = 1,
                            ContributorId = 2,
                            CorrectAnswer = "A",
                            CreatedDate = new DateTime(2025, 9, 30, 21, 18, 46, 942, DateTimeKind.Local).AddTicks(2539),
                            Difficulty = "Easy",
                            Explanation = "SQL stands for Structured Query Language, used for managing relational databases.",
                            IsActive = true,
                            IsApproved = true,
                            OptionA = "Structured Query Language",
                            OptionB = "Simple Query Language",
                            OptionC = "Sequential Query Language",
                            OptionD = "Standard Query Language",
                            Question = "What does SQL stand for?",
                            Tags = "SQL, database",
                            Topic = "Database",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("InterviewCracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("GitHubProfile")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LinkedInProfile")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("Organization")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.Property<string>("Role")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 940, DateTimeKind.Local).AddTicks(2935),
                            Email = "admin@admin.com",
                            IsActive = true,
                            Name = "System Admin",
                            Password = "admin123",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 940, DateTimeKind.Local).AddTicks(3251),
                            Email = "contributor@test.com",
                            IsActive = true,
                            Name = "John Doe",
                            Password = "test123",
                            Role = "Contributor"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 10, 2, 21, 18, 46, 940, DateTimeKind.Local).AddTicks(3260),
                            Email = "student@test.com",
                            IsActive = true,
                            Name = "Jane Smith",
                            Password = "test123",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("InterviewCracker.Models.CodingQuestion", b =>
                {
                    b.HasOne("InterviewCracker.Models.College", null)
                        .WithMany()
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewCracker.Models.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewCracker.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InterviewCracker.Models.CollegeCompany", b =>
                {
                    b.HasOne("InterviewCracker.Models.College", "College")
                        .WithMany("CollegeCompanies")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewCracker.Models.Company", "Company")
                        .WithMany("CollegeCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterviewCracker.Models.MCQ", b =>
                {
                    b.HasOne("InterviewCracker.Models.College", null)
                        .WithMany()
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewCracker.Models.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewCracker.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
